import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Clone Company Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen w-full justify-between">
          <div className="z-50 top-0 sticky">
            <Navbar />
          </div>
          <div className="flex h-max items-center justify-center">
            {children}
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
